# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # always use Vagrants insecure key
  config.ssh.insert_key = false
  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end

  cluster = {
    "master" => { :ip => "192.168.56.1", :mem => 1024,  :cpu => 1 },
    # "node1" => { :ip => "192.168.56.2", :mem => 1024,  :cpu => 1 },
    # "node2" => { :ip => "192.168.56.3", :mem => 1024,  :cpu => 1 },
  }

  cluster.each_with_index do | (hostname, info), index |
    config.vm.define hostname do | host |
      host.vm.box = "centos7"
      host.vm.provider "virtualbox" do |v|
        v.name   = "k3s-#{hostname}"
        v.memory = info[:mem]
        v.cpus   = info[:cpu]
      end
      host.vm.hostname = hostname
      host.vm.network "private_network", ip: info[:ip]
    end
  end
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 20080
  config.vm.network "forwarded_port", guest: 8080, host: 28080
  config.vm.network "forwarded_port", guest: 8001, host: 28001
  config.vm.network "forwarded_port", guest: 8002, host: 28002
  config.vm.network "forwarded_port", guest: 443, host: 20443
end
